parameters:
    changePasswordRouteName: 'change_password'
    passwordMaxDaysOld: 30
    easyadmin.changePasswordControllerName: null
    easyadmin.changePasswordControllerActionName: null

services:
    RobinBrackez\PasswordExpirationBundle\EventListener\PasswordExpirationListener:
        autowire: true
        arguments:
            $security: '@security.helper'
            $changePasswordRouteName: '%changePasswordRouteName%'
            $passwordMaxDaysOld: '%passwordMaxDaysOld%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    RobinBrackez\PasswordExpirationBundle\EventListener\PasswordChangeListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'preUpdate' }

    RobinBrackez\PasswordExpirationBundle\Service\EasyAdminWrapper:
        autowire: true
        arguments:
            $changePasswordControllerName: '%easyadmin.changePasswordControllerName%'
            $changePasswordCrudActionName: '%easyadmin.changePasswordControllerActionName%'
        calls:
            - setAdminUrlGenerator: ['@?EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator']